[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "packer"
version = "0.10.0"
description = "A Python automation tool that streamlines python software release workflows"
dependencies = [
    "ollama",
    "pygithub",
    "requests",
    "platformdirs",
    "GitPython",
    "dirhash",
    "pyinstaller",
    "tomlkit",
    "pyzipper"
]

[tool.setuptools]
include-package-data = true
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
packer = ["assets/*"]

[project.scripts]
packer = "packer.main:main"