[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "packer"
version = "0.6.0"
description = "A short description of my packer project"
dependencies = [
    "ollama",
    "pygithub",
    "requests",
    "platformdirs",
    "GitPython",
    "dirhash",
    "pyinstaller",
    "tomlkit"
]

[tool.setuptools.packages.find]
where = ["src"]  # This tells setuptools to look for packages inside 'src'

[project.scripts]
packer = "packer.main:main"